name: Release Webhook

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send release notification webhook
        run: |
          RELEASE_NAME="${{ github.event.release.name }}"
          TAG_NAME="${{ github.event.release.tag_name }}"
          URL="${{ github.event.release.html_url }}"

          MSG="🚀 New release: $RELEASE_NAME ($TAG_NAME) - $URL"

          curl -X POST "https://stoat.chat/api/webhooks/01KM0VR768BP5W0CAB54ASK2QP/ruEjyZDLwgOip8ClH_oURUPu3LehRz_7yEXb1VVdO5ZuX2d4Pd8-z7aN0aQWmbrj" \
          -H "Content-Type: application/json" \
          -d "{\"content\":\"$MSG\"}"
